name: Build & Tests

on:
  push:
    branches:  '**'
  pull_request:
    branches:  '**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      minio:
        image: minio/minio
        volumes:
          - ${{ github.workspace }}/data:/data
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        options: --entrypoint "minio server /data" --health-cmd "curl -f http://localhost:9000/minio/health/live" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
    - name: Test with unittest and coverage-report
      env:
        TOKEN: ${{ secrets.IBMQ_TOKEN }}
      run: |
        coverage run --branch --include 'app/*' -m unittest discover
        coverage report
        coverage xml
    - name: Upload Coverage to Codecov
      timeout-minutes: 1
      uses: codecov/codecov-action@v2
      with:
        token: "f6e9a3db-8d40-468c-817b-1acabeabc72e"
        fail_ci_if_error: false
        verbose: true
        files: ./coverage.xml
        flags: unittests
    - name: Check code style
      run: black --check .